package juno.view.util;

public enum Constant {

    THROW_EXCEPTION,

    RED_BUTTON,
    BLUE_BUTTON,
    YELLOW_BUTTON,
    CYAN_BUTTON,
    GREEN_BUTTON,

    RED_LABEL,
    BLUE_LABEL,
    YELLOW_LABEL,
    CYAN_LABEL,
    GREEN_LABEL,

    KEEP_IMAGE,
    KEEP_ROLLOVER_IMAGE,
    KEEP_SELECTED_IMAGE,
    KEEP_ROLLOVER_SELECTED_IMAGE;
}
